begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, extensions;
select no_plan();
insert into auth.users(id,email) values ('00000000-0000-0000-0000-000000000001','admin@test.invalid'),('00000000-0000-0000-0000-000000000002','visitor@test.invalid');
insert into public.admin_users(user_id) values ('00000000-0000-0000-0000-000000000001');
insert into public.service_categories(id,name,slug,active) values (9001,'Visible','visible',true),(9002,'Hidden','hidden',false);
insert into public.services(id,name,slug,price_type,active,category_id) values (9001,'Visible','visible','quote',true,9001),(9002,'Hidden','hidden','quote',false,9001),(9003,'Hidden category','hidden-category','quote',true,9002);
update public.banner set enabled=false,message='Private draft' where id=1;
select ok((select relrowsecurity from pg_class where oid='public.business_hours'::regclass),'business_hours has RLS');
select ok((select relrowsecurity from pg_class where oid='public.service_categories'::regclass),'service_categories has RLS');
select ok((select relrowsecurity from pg_class where oid='public.services'::regclass),'services has RLS');
select ok((select relrowsecurity from pg_class where oid='public.banner'::regclass),'banner has RLS');
select ok((select relrowsecurity from pg_class where oid='public.admin_users'::regclass),'admin_users has RLS');
set local role anon;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',true);
select is((select count(*) from business_hours),7::bigint,'Public can read seven days');
select is((select count(*) from services where id>=9001),1::bigint,'Only active services in active categories are public');
select is((select count(*) from service_categories where id>=9001),1::bigint,'Only active categories are public');
select is((select count(*) from banner),0::bigint,'Disabled banner draft is private');
select throws_ok($$insert into business_hours(day_of_week,day_name,is_open,display_order) values(6,'Saturday',false,6)$$,'42501',null,'anon cannot insert business_hours');
select throws_ok($$update business_hours set id=id$$,'42501',null,'anon cannot write business_hours');
select throws_ok($$delete from business_hours$$,'42501',null,'anon cannot write business_hours');
select throws_ok($$insert into service_categories(name,slug) values('Attack','attack')$$,'42501',null,'anon cannot insert service_categories');
select throws_ok($$update service_categories set id=id$$,'42501',null,'anon cannot write service_categories');
select throws_ok($$delete from service_categories$$,'42501',null,'anon cannot write service_categories');
select throws_ok($$insert into services(name,slug,price_type) values('Attack','attack','quote')$$,'42501',null,'anon cannot insert services');
select throws_ok($$update services set id=id$$,'42501',null,'anon cannot write services');
select throws_ok($$delete from services$$,'42501',null,'anon cannot write services');
select throws_ok($$insert into banner(id) values(1)$$,'42501',null,'anon cannot insert banner');
select throws_ok($$update banner set id=id$$,'42501',null,'anon cannot write banner');
select throws_ok($$delete from banner$$,'42501',null,'anon cannot write banner');
select throws_ok($$insert into admin_users(user_id) values('00000000-0000-0000-0000-000000000002')$$,'42501',null,'Cannot self-promote');
select throws_ok($$delete from admin_users$$,'42501',null,'Cannot delete admin membership');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',true);
select is((select count(*) from business_hours),7::bigint,'Public can read seven days');
select is((select count(*) from services where id>=9001),1::bigint,'Only active services in active categories are public');
select is((select count(*) from service_categories where id>=9001),1::bigint,'Only active categories are public');
select is((select count(*) from banner),0::bigint,'Disabled banner draft is private');
select throws_ok($$insert into business_hours(day_of_week,day_name,is_open,display_order) values(6,'Saturday',false,6)$$,'42501',null,'authenticated cannot insert business_hours');
with changed as (update business_hours set id=id returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot update business_hours');
with changed as (delete from business_hours returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot delete business_hours');
select throws_ok($$insert into service_categories(name,slug) values('Attack','attack')$$,'42501',null,'authenticated cannot insert service_categories');
with changed as (update service_categories set id=id returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot update service_categories');
with changed as (delete from service_categories returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot delete service_categories');
select throws_ok($$insert into services(name,slug,price_type) values('Attack','attack','quote')$$,'42501',null,'authenticated cannot insert services');
with changed as (update services set id=id returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot update services');
with changed as (delete from services returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot delete services');
select throws_ok($$insert into banner(id) values(1)$$,'42501',null,'authenticated cannot insert banner');
with changed as (update banner set id=id returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot update banner');
with changed as (delete from banner returning *) select is((select count(*) from changed),0::bigint,'Non-admin cannot delete banner');
select throws_ok($$insert into admin_users(user_id) values('00000000-0000-0000-0000-000000000002')$$,'42501',null,'Cannot self-promote');
select throws_ok($$delete from admin_users$$,'42501',null,'Cannot delete admin membership');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
select is((select count(*) from admin_users),1::bigint,'Admin can verify own membership');
select is((select count(*) from services where id>=9001),3::bigint,'Admin sees hidden services');
select is((select count(*) from banner),1::bigint,'Admin sees disabled banner');
with changed as (update business_hours set id=id returning *) select is((select count(*)>0 from changed),true,'Admin can update business_hours');
with changed as (update service_categories set id=id returning *) select is((select count(*)>0 from changed),true,'Admin can update service_categories');
with changed as (update services set id=id returning *) select is((select count(*)>0 from changed),true,'Admin can update services');
with changed as (update banner set id=id returning *) select is((select count(*)>0 from changed),true,'Admin can update banner');
select lives_ok($$insert into service_categories(name,slug) values('New','new')$$,'Admin can insert categories with identity');
select lives_ok($$insert into services(name,slug,price,price_type) values('New','new',12.50,'fixed')$$,'Admin can insert services with identity');
with changed as (delete from services where slug='new' returning *) select is((select count(*) from changed),1::bigint,'Admin can delete services');
with changed as (delete from service_categories where slug='new' returning *) select is((select count(*) from changed),1::bigint,'Admin can delete categories');
with changed as (delete from business_hours where day_of_week=6 returning *) select is((select count(*) from changed),1::bigint,'Admin can delete hours');
select lives_ok($$insert into business_hours(day_of_week,day_name,is_open,display_order) values(6,'Saturday',false,6)$$,'Admin can insert hours');
with changed as (delete from banner returning *) select is((select count(*) from changed),1::bigint,'Admin can delete banner');
select lives_ok($$insert into banner(id,enabled,message) values(1,true,'Hello')$$,'Admin can insert banner');
select throws_ok($$insert into admin_users(user_id) values('00000000-0000-0000-0000-000000000002')$$,'42501',null,'Even CMS admins cannot grant membership');
select throws_ok($$update banner set link_text='Click',link_url='javascript:alert(1)'$$,'23514',null,'Reject script URLs');
select throws_ok($$update banner set message='<script>alert(1)</script>'$$,'23514',null,'Reject banner HTML');
select throws_ok($$update banner set message=''$$,'23514',null,'Enabled banner needs a message');
select throws_ok($$insert into banner(id) values(2)$$,'23514',null,'Banner is a singleton');
select throws_ok($$update business_hours set is_open=true,open_time='19:00',close_time='08:00' where day_of_week=1$$,'23514',null,'Closing time follows opening');
select throws_ok($$insert into services(name,slug,price_type,price) values('Bad','bad','fixed',null)$$,'23514',null,'Fixed price is required');
select throws_ok($$insert into services(name,slug,price_type,price) values('Bad','bad','quote',12)$$,'23514',null,'Quote price must be null');
select throws_ok($$insert into services(name,slug,price_type,price) values('Bad','bad','fixed',-1)$$,'23514',null,'Negative prices rejected');
reset role;
set local role anon;
select is((select message from banner),'Hello','Enabled banner is public');
reset role;
select * from finish();
rollback;
