-- CMS authorization uses an explicit allowlist, never merely the authenticated role.
create type public.price_type as enum ('fixed','starting_at','per_pound','quote');
create type public.banner_style as enum ('info','success','warning','promotion');
create table public.admin_users (
 user_id uuid primary key references auth.users(id) on delete cascade,
 created_at timestamptz not null default now()
);
create table public.business_hours (
 id bigint generated by default as identity primary key,
 day_of_week smallint not null unique check(day_of_week between 0 and 6),
 day_name text not null check (day_name = (array['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])[day_of_week + 1]),
 is_open boolean not null default true, open_time time, close_time time,
 display_order smallint not null, updated_at timestamptz not null default now(),
 constraint valid_hours check ((not is_open and open_time is null and close_time is null) or
 (is_open and open_time is not null and close_time is not null and close_time > open_time))
);
create table public.service_categories (
 id bigint generated by default as identity primary key,
 name text not null check(length(trim(name)) between 1 and 100),
 slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
 display_order integer not null default 0, active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.services (
 id bigint generated by default as identity primary key,
 category_id bigint references public.service_categories(id) on delete set null,
 name text not null check(length(trim(name)) between 1 and 100),
 slug text not null unique check(slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
 description text check(length(description) <= 1000), price numeric(10,2),
 price_type public.price_type not null default 'fixed', display_order integer not null default 0,
 active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint service_price_valid check ((price_type = 'quote' and price is null) or
 (price_type <> 'quote' and price is not null and price >= 0))
);
create index services_category_id_idx on public.services(category_id);
create table public.banner (
 id bigint primary key default 1 check(id=1), enabled boolean not null default false,
 message text check(length(message)<=250 and message !~ '[<>]'),
 link_text text check(length(link_text)<=50 and link_text !~ '[<>]'), link_url text,
 style public.banner_style not null default 'info', updated_at timestamptz not null default now(),
 constraint banner_enabled_message check(not enabled or coalesce(length(trim(message)),0)>0),
 constraint banner_link_pair check((link_text is null and link_url is null) or
 (coalesce(length(trim(link_text)),0)>0 and link_url is not null)),
 constraint banner_safe_url check(link_url is null or
 (length(link_url)<=2048 and link_url ~ '^https?://[^[:space:]/?#@]+([/?#][^[:space:]]*)?$' and link_url !~ '[<>\\]'))
);
create function public.cms_updated_at() returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end; $$;
revoke all on function public.cms_updated_at() from public, anon, authenticated;
alter table public.business_hours enable row level security;
revoke all on public.business_hours from public, anon, authenticated;
alter table public.service_categories enable row level security;
revoke all on public.service_categories from public, anon, authenticated;
alter table public.services enable row level security;
revoke all on public.services from public, anon, authenticated;
alter table public.banner enable row level security;
revoke all on public.banner from public, anon, authenticated;
alter table public.admin_users enable row level security;
revoke all on public.admin_users from public, anon, authenticated;
grant select on public.admin_users to authenticated;
create policy admin_self_read on public.admin_users for select to authenticated using(user_id=(select auth.uid()));
-- Membership may only be granted by trusted SQL/dashboard operations.
grant select on public.business_hours to anon;
grant select, insert, update, delete on public.business_hours to authenticated;
create policy public_read on public.business_hours for select to anon, authenticated using (true);
create policy admin_read on public.business_hours for select to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_insert on public.business_hours for insert to authenticated with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_update on public.business_hours for update to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid()))) with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_delete on public.business_hours for delete to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create trigger cms_updated_at before update on public.business_hours for each row execute function public.cms_updated_at();
grant select on public.service_categories to anon;
grant select, insert, update, delete on public.service_categories to authenticated;
create policy public_read on public.service_categories for select to anon, authenticated using (active);
create policy admin_read on public.service_categories for select to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_insert on public.service_categories for insert to authenticated with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_update on public.service_categories for update to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid()))) with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_delete on public.service_categories for delete to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create trigger cms_updated_at before update on public.service_categories for each row execute function public.cms_updated_at();
grant select on public.services to anon;
grant select, insert, update, delete on public.services to authenticated;
create policy public_read on public.services for select to anon, authenticated using (active and (category_id is null or exists (select 1 from public.service_categories c where c.id=category_id and c.active)));
create policy admin_read on public.services for select to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_insert on public.services for insert to authenticated with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_update on public.services for update to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid()))) with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_delete on public.services for delete to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create trigger cms_updated_at before update on public.services for each row execute function public.cms_updated_at();
grant select on public.banner to anon;
grant select, insert, update, delete on public.banner to authenticated;
create policy public_read on public.banner for select to anon, authenticated using (enabled);
create policy admin_read on public.banner for select to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_insert on public.banner for insert to authenticated with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_update on public.banner for update to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid()))) with check (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create policy admin_delete on public.banner for delete to authenticated using (exists (select 1 from public.admin_users where user_id=(select auth.uid())));
create trigger cms_updated_at before update on public.banner for each row execute function public.cms_updated_at();
revoke all on sequence public.business_hours_id_seq from public, anon, authenticated;
grant usage on sequence public.business_hours_id_seq to authenticated;
revoke all on sequence public.service_categories_id_seq from public, anon, authenticated;
grant usage on sequence public.service_categories_id_seq to authenticated;
revoke all on sequence public.services_id_seq from public, anon, authenticated;
grant usage on sequence public.services_id_seq to authenticated;
